version: '3'
services:
  config-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ETCD_HOST=etcd
  
  etcd:
    image: bitnami/etcd:latest
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
